name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Download SQLite Amalgamation
      run: |
        curl -sSfL -o sqlite.zip https://www.sqlite.org/2024/sqlite-amalgamation-3470000.zip
        unzip sqlite.zip
        mv sqlite-amalgamation-3470000/* .

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
